### ISSUE TITLE
Low: Price for item is too long and is using 2 lines

### ISSUE THREAD

**Issue by Ckozoh** [printdotio/printio-android-sdk#100]
If you notice the price of the item in the top right corner, once in the triple digits the price is too long and is using 2 lines.

![screenshot_2014-10-29-10-37-16](https://cloud.githubusercontent.com/assets/8116157/4830992/79c3599c-5f91-11e4-9361-d989f8c1147d.png)

**Comment by bomberaya** [comment]
@Ckozoh The price has been removed from the top bar in v2.0.3, so this is fixed.

**Comment by AustenB** [comment]
What about for phone case product?

On Mon, Mar 9, 2015 at 11:07 AM, bomberaya <notifications@github.com> wrote:

> @Ckozoh <https://github.com/Ckozoh> The price has been removed from the
> top bar in v2.0.3, so this is fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/100#issuecomment-77870807>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
@AustenB It was removed from iOS version, so we removed it from Android too.
