### ISSUE TITLE
Medium: Rotating in edit issue

### ISSUE THREAD

**Issue by Ckozoh** [printdotio/printio-android-sdk#111]
Samsung GS3 4.1.1

While trying to rotate a photo in edit, it will be resized and once returned to the original position, the image is cropped.

![](http://i1240.photobucket.com/albums/gg494/chkotest2/GIF%20Maker/AC297440-E4E6-44FE-9B8C-46719B63A198_zpsytdb3wlf.gif)

**Comment by itscam** [comment]
@bomberaya I believe this is fixed. Not seeing it now.
