### ISSUE TITLE
Low: Phone cases - Display Android cases first

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#115]
If a user is ordering a phone case, odds are they want to buy a case for their device. An Android user was confused when the first several products displayed were iPhone cases.

**Comment by vladgets** [comment]
When I put in my project the code in the mainActivity:  PIO.start(this, null);
It just returns and nothing happens. 
Could you explain me why could it happen and what I do wrong?

**Comment by vladopajic** [comment]
Fixed in 2.1.9.
