### ISSUE TITLE
High: When choosing a new shipping-to country, defaults to Afghanistan 

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#116]
Newest SDK version.

Tap on the Shipping To dropdown, pop-up appears asking user if they want to ship to Afghanistan. Also, along the same lines of the currency screen, could we add the United States to the top of the country list?

![5secondsapp 17](https://cloud.githubusercontent.com/assets/8051364/5620821/b07bfa80-94ec-11e4-9e0b-ed84238d9630.gif)

**Comment by vladgets** [comment]
When I put in my project the code in the mainActivity:  PIO.start(this, null);
It just returns and nothing happens. 
Could you explain me why could it happen and what I do wrong?

**Comment by vladopajic** [comment]
@itscam Fixed, please verify.

**Comment by itscam** [comment]
Fix verified.
