### ISSUE TITLE
Widget does not work

### ISSUE THREAD

**Issue by vladgets** [printdotio/printio-android-sdk#117]
When I put in my project the code in the mainActivity: PIO.start(this, null);
It just returns and nothing happens. 
Could you explain me why could it happen and what I do wrong?

**Comment by bomberaya** [comment]
Have you included the required code listed here?
https://github.com/printdotio/printio-android-sdk/blob/master/README.md#printio-quick-start

**Comment by vladgets** [comment]
Yes. It took me some effort making it to compile. I had to change some configuration, since I use Android studio and not Eclipse and latest SDK and building tools. So, I included this module and succeeded it to build. But then when I call to the command: PIO.start(this, null);
from my main activity, nothing is launched.

**Comment by bomberaya** [comment]
Take a look at logcat. Are there any error/debug messages or exceptions thrown?

**Comment by vladgets** [comment]
My question, should I keep AndroidManifest.xml inside of the printSDK module in addition to my project AndroidManifest.xml file? Because there is defined an additional app: PIO.

When I keep this additional Manifest file, I get an error message:
  java.lang.RuntimeException: Unable to instantiate application print.io.PIO: java.lang.ClassCastException: print.io.PIO cannot be cast to android.app.Application

When I clean this file and run the project I get the message:
W/System.err﹕ at com.vladgets.picksu.MainActivity.onCreate(MainActivity.java:17)
For the line: PIO.start(this, null);

**Comment by bomberaya** [comment]
@vladgets Please try integrating the latest version
