### ISSUE TITLE
Medium: User prompted to choose a shipping country when SDK is first opened

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#118]
I believe this is a new issue. Can we detect where the user is located to avoid this step?

![5secondsapp 1](https://cloud.githubusercontent.com/assets/8051364/5745044/1d35648e-9be3-11e4-923d-970814b875be.gif)

**Comment by vladopajic** [comment]
@itscam Yes, it will be available in newest release.

**Comment by barnbucket** [comment]
Is this new? Before we upgraded to the newer version this was set automatically. Now we are getting the unnecessary screen. 

If this is a new change please point us to the documentation on how to change it.

**Comment by barnbucket** [comment]
https://github.com/printdotio/printio-android-sdk/blob/develop/NEW-DOCS-WIP.md#country-currency-and-language

There is a way to set the default country code, but by setting PIO.setCountryOnFeaturedProducts(true); this should automatically default to us

Ours is no longer automatically defaulting to US.

**Comment by bomberaya** [comment]
@barnbucket This will be fixed in the next version of the SDK. It is possible that it has already been fixed, but I'm delaying the next version because of another issue that we are currently working on. A new version will be available at the end of January, at the latest.

**Comment by bomberaya** [comment]
@barnbucket Fixed in 2.0.4, please verify

**Comment by itscam** [comment]
Fix verified.
