### ISSUE TITLE
High: Crash in production  java.lang.NullPointerException

### ISSUE THREAD

**Issue by barnbucket** [printdotio/printio-android-sdk#119]
Our app is logging a crash in our production app. It is our highest occurring crash right now. We updated our SDK on Dec 23rd.

java.lang.NullPointerException
at print.io.ActivityCountry$6.run(Unknown Source)
at java.lang.Thread.run(Thread.java:841)

**Comment by AustenB** [comment]
@bomberaya what is the update on this one?

**Comment by AustenB** [comment]
@bomberaya did this one get fixed?

**Comment by bomberaya** [comment]
@AustenB @barnbucket Fixed in 2.0.3

**Comment by bomberaya** [comment]
@barnbucket any updates on this? :)
