### ISSUE TITLE
High: Error uploading product photos for high-image count products

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#120]
We are receiving the following error when attempting to pay for a minibook/tinybook product. We have tried a combination of different sources including Facebook, Instagram and Photobucket. ![screenshot_2015-02-18-16-16-49](https://cloud.githubusercontent.com/assets/8051364/6258912/22bb45aa-b78a-11e4-9bf3-e929ca8c711f.png)

When uploading from the phone source I get stuck on a loading screen. 

![screenshot_2015-02-18-16-29-49](https://cloud.githubusercontent.com/assets/8051364/6259035/763fe1b2-b78b-11e4-8cf0-f48f1969006f.png)

**Comment by bomberaya** [comment]
@itscam Fixed in 2.0.3

**Comment by itscam** [comment]
Fix verified.
