### ISSUE TITLE
Shower curtain images problem

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-android-sdk#121]
Orders 136597 and 134234.
Images aren't generated right. Please see product preview vs. how shower curtain image was generated!

![preview](https://cloud.githubusercontent.com/assets/10849553/6350272/a56d7ed0-bc32-11e4-8053-4e2dfc7ee0b0.jpg)

@bomberaya @Ivan1985 @AustenB

**Comment by mkontic** [comment]
Also order 122280.

**Comment by AustenB** [comment]
This is priority

**Comment by bomberaya** [comment]
@AustenB @mkontic OK guys, I checked this out, this order was made using android v114, which is an old version of the SDK.
This bug has been fixed since, but it will still appear from time to time because some users might not update their apps.

**Comment by AustenB** [comment]
What is our latest app update?

We can also force users to update app?

When are we doing a master push to repo?

On Tue, Feb 24, 2015 at 10:22 AM, bomberaya <notifications@github.com>
wrote:

> Closed #121 <https://github.com/printdotio/printio-android-sdk/issues/121>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/121#event-240980082>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
v114 is the last update. We have one more bug to fix before we do the update, I'm working on it. I will try to push the update ASAP.

We can't explicitly force users to update the app. Maybe we could try sending push notifications telling them to update?

Same answer as the first question, as soon as we fix this bug, and I hope real soon.

**Comment by AustenB** [comment]
But they are using the latest.

Are you sure its fixed in the newest? You have to have ivan/milos test
shower curtains etc.

On Tue, Feb 24, 2015 at 10:34 AM, bomberaya <notifications@github.com>
wrote:

> v114 is the last update. We have one more bug to fix before we do the
> update, I'm working on it. I will try to push the update ASAP.
>
> We can't explicitly force users to update the app. Maybe we could try
> sending push notifications telling them to update?
>
> Same answer as the first question, as soon as we fix this bug, and I hope
> real soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/121#issuecomment-75778619>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
Yes, they are, but it's been a while since we updated it and it's crying for an update.

We haven't seen this bug in a long time so I'm pretty sure it's fixed in v116.

**Comment by Ivan1985** [comment]
@AustenB @bomberaya @mkontic I've already tested it and works good. I agree with @bomberaya, that was an old issue.

**Comment by AustenB** [comment]
Ok from now on we use branches for everything.

We need to release new versions with bug fixes every two weeks.

On Tue, Feb 24, 2015 at 10:54 AM, Ivan Ignjatovic <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> @bomberaya
> <https://github.com/bomberaya> @mkontic <https://github.com/mkontic> I've
> already tested it and works good. I agree with @bomberaya
> <https://github.com/bomberaya>, that was an old issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/121#issuecomment-75782776>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by mkontic** [comment]
@AustenB @Ivan1985 @bomberaya So basically, I can tell the customer to update the app and it should be fine?

**Comment by bomberaya** [comment]
@AustenB I agree

@mkontic No, unfortunately. I think they will need to create the order again. I'm not sure if you are able to manually correct the imgmanip string on server...

**Comment by mkontic** [comment]
@bomberaya No, I get that this order needs fixing on our end, but for theirs next purchases, it will be enough just to update the app, right?

**Comment by bomberaya** [comment]
@mkontic When we publish the new version, yes. Currently there is no newer version to update to.

**Comment by mkontic** [comment]
@bomberaya Thanks, that's the answer I was looking for!

**Comment by bomberaya** [comment]
@mkontic Anytime :)
