### ISSUE TITLE
Medium: Images not rotated correctly for Samsung devices

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#122]
Tested with a GS3 and GS5. Not an issue on Nexus 5 and other LG devices.

- Take landscape and portrait photos from all angles
- Create a product and select those photos

Notice that the thumbnail images have not been correctly rotated. Images will display this way in the collage preview. This is also an issue on HelloPics.

![screenshot_2015-03-23-13-52-13](https://cloud.githubusercontent.com/assets/8051364/6789164/e7f24d80-d163-11e4-970d-55442a8d0f6d.png)
![screenshot_2015-03-23-13-40-55](https://cloud.githubusercontent.com/assets/8051364/6789171/f8ee0714-d163-11e4-98e5-54933141d89d.png)

**Comment by AustenB** [comment]
@itscam is this the default way they are saved on the phone? if so than how would we be able to fix/modify it?

**Comment by vladopajic** [comment]
@itscam Fixed in 2.2.2, please verify.
