### ISSUE TITLE
Medium: Shipping address auto-complete issue

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#123]
All devices, newest SDK version on production

- Start typing your shipping address in the street form. 
- Tap on desired selection

Street address is not fully entered. Number added, but not the street name.

![5secondsapp 15](https://cloud.githubusercontent.com/assets/8051364/6793180/ba76cac0-d186-11e4-99e4-71abe5006ba4.gif)

**Comment by bomberaya** [comment]
@itscam Fixed: 2.1.0

**Comment by itscam** [comment]
Fix verified.
