### ISSUE TITLE
Low/Medium: Shopping cart badge positioning 

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#124]
All devices, newest sdk version, on production.

For some products, such as prints, thick prints, stickerbooks, tinybooks, minibooks, coasters, and magnetgrams, the shopping cart on the image quality and cropping screen doesn't match the standard shopping cart.

Also, the sidebar menu shopping cart doesn't match either.

![screenshot_2015-03-23-18-20-33](https://cloud.githubusercontent.com/assets/8051364/6793394/65f8ed04-d189-11e4-993c-f1cbad522364.png)
![screenshot_2015-03-23-18-19-29](https://cloud.githubusercontent.com/assets/8051364/6793395/685e67c2-d189-11e4-9dba-29dd38dc516a.png)

**Comment by bomberaya** [comment]
@itscam These are the screenshots from my phone, using your shopping cart icon.
Are you doing something differently?
I made the following adjustments to following xml files:

`res/values/dimens.xml`
```xml
    <dimen name="cart_items_quantity_top_offset">0dip</dimen>
    <dimen name="cart_items_quantity_right_offset">0dip</dimen>
```

`res/values-sw330dp/dimens.xml`
```xml
    <dimen name="cart_items_quantity_top_offset">0dip</dimen>
    <dimen name="cart_items_quantity_right_offset">0dip</dimen>
```
![screenshot_2015-03-26-19-23-49](https://cloud.githubusercontent.com/assets/3813595/6853938/5568d168-d3ee-11e4-8a32-585313b5f3ba.png)
![screenshot_2015-03-26-19-24-23](https://cloud.githubusercontent.com/assets/3813595/6853940/58bd9498-d3ee-11e4-89a1-ce7d4643f055.png)

**Comment by itscam** [comment]
@bomberaya 

![screenshot_2015-04-01-11-08-49](https://cloud.githubusercontent.com/assets/8051364/6946791/fa132860-d85f-11e4-86cd-48f97339c86c.png)

![screenshot_2015-04-01-11-09-09](https://cloud.githubusercontent.com/assets/8051364/6946790/fa12f322-d85f-11e4-9ae8-a6037d68dd33.png)

**Comment by AustenB** [comment]
@itscam let us know if the emailed solution fixed it
