### ISSUE TITLE
Medium: Choose options screen is broken for some products

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#125]
Nexus 5 and GS5, newest SDK build. On production.

Some items have been shifted toward the bottom of the screen. I have noticed this for framed prints, canvas wraps and metal prints.

![screenshot_2015-03-25-15-51-44](https://cloud.githubusercontent.com/assets/8051364/6836482/0aab1db6-d308-11e4-81ad-239dad0a9f54.png)

**Comment by AustenB** [comment]
THe shift down was on-purpose --> clearly the price being that far down on
the page was not. It shouldn't have the price above the couch.



On Wed, Mar 25, 2015 at 6:07 PM, Cameron Bradley <notifications@github.com>
wrote:

> Nexus 5 and GS5, newest SDK build. On production.
>
> Some items have been shifted toward the bottom of the screen. I have
> noticed this for framed prints, canvas wraps and metal prints.
>
> [image: screenshot_2015-03-25-15-51-44]
> <https://cloud.githubusercontent.com/assets/8051364/6836482/0aab1db6-d308-11e4-81ad-239dad0a9f54.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/125>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
@itscam This was done intentionally. The idea is to display the prints/canvases above the couch, so that the user gets the idea of their relative size. Although the second item on your screenshot (14x16 inch Frame) obviously doesn't stand where it should be...
Could you attach the same screenshot but with the following phone setting enabled:
Settings -> Developer Options -> Advanced -> Show layout bounds
Thanks

Lol Austen, you beat me to it :)

**Comment by bomberaya** [comment]
Btw the price over couch looks cool to me

**Comment by itscam** [comment]
Canvas wraps. You can see the product image is not a transparent png. Price is not visible.  

![screenshot_2015-03-25-15-51-44](https://cloud.githubusercontent.com/assets/8051364/6836710/53150254-d30a-11e4-9453-db31ee45542b.png)

**Comment by bomberaya** [comment]
@itscam Price not visible issue is already fixed and will be pushed in the next release

**Comment by bomberaya** [comment]
@itscam I agree, those images should be fixed on serverside.

**Comment by itscam** [comment]
@bomberaya 
![screenshot_2015-03-25-16-24-33](https://cloud.githubusercontent.com/assets/8051364/6836844/9e157e5e-d30b-11e4-9a14-7563b24fdc83.png)

**Comment by itscam** [comment]
@bomberaya That alternates every product. One is set on the couch, the next over the couch, and so on.

**Comment by itscam** [comment]
![5secondsapp 16](https://cloud.githubusercontent.com/assets/8051364/6836924/75e1cdf6-d30c-11e4-9e63-2dcd1845c03b.gif)

**Comment by AustenB** [comment]
We can update the assets to fix it -- im surprised they weren't jagged in
the old version in live

On Wed, Mar 25, 2015 at 6:32 PM, Cameron Bradley <notifications@github.com>
wrote:

> [image: 5secondsapp 16]
> <https://cloud.githubusercontent.com/assets/8051364/6836924/75e1cdf6-d30c-11e4-9e63-2dcd1845c03b.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/125#issuecomment-86237974>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
@itscam I think I know what is the issue.
The square images (for example 14x14 inch) are 280x280px
and rectangle images (14x16 inch) are 370x280px.
I am scaling the images to same widths, so they end up having different heights.
I can fix this on client side, but the strange thing is that everything looks fine on our devices (tested on Nexus 5, Galaxy S4 and HTC One M8)

This is the screenshot from Nexus 5:
![5e258d7876cf8f80786e75f5c516644f9053bc70c499c8fe2fpimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/3813595/6837213/4242057c-d34a-11e4-89e7-2136d914f61f.jpg)

**Comment by bomberaya** [comment]
@itscam @AustenB I will mark this as a bug (non-uniform image heights).

Regarding image (non)transparency issue, images need to be updated on server.

**Comment by bomberaya** [comment]
@itscam Fixed: v2.1.2

**Comment by itscam** [comment]
@bomberaya @AustenB I suppose it could be an issue with the font we are using, but the price is displayed on the couch on the Nexus 5(1080p, a5.1) and Moto G(720p, a4.4.4). However, this does look good on other devices, including the GS3 and GS5.

Nexus 5
![screenshot_2015-04-01-16-33-10](https://cloud.githubusercontent.com/assets/8051364/6954603/caa49c40-d890-11e4-8550-0ad529644be4.png)
