### ISSUE TITLE
High: One item number for multiple photos

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-android-sdk#127]
Customer uploaded 171 images for print glossy 4x4, but they generated as one single item (Item 382991). However, we can see all of the images on our end, but it appears they were sent to our vendor as one item and they received only first image. Customer got one image in 171 copies. 

We've never received orders like this - every image always has different item number. 

Same goes for Item 382993. 

https://admin-v2.print.io/Home#/orders/151785/images

Additionally, customer placed one more order and same thing happened:
https://admin-v2.print.io/Home#/orders/154195/images

@bomberaya @Ivan1985 @AustenB

**Comment by bomberaya** [comment]
@mkontic, can you please give me an example of a similar order (made from Android app) that worked fine (same product but older order)? I need it to check something. Thanks!

**Comment by mkontic** [comment]
@bomberaya I searched literally every HP orders with prints (District Photo vendor) and I couldn't find a single one placed via android app.

**Comment by bomberaya** [comment]
@mkontic Can you find any order with any of the following products (regardless of vendor) placed via Android app:
minibooks, tinybooks, metal magnets, stickerbooks, thick prints, magnetgram?

**Comment by mkontic** [comment]
@bomberaya Here's a few:

https://admin-v2.print.io/Home#/orders/99411/summary
https://admin-v2.print.io/Home#/orders/96197/summary
https://admin-v2.print.io/Home#/orders/90593/summary
https://admin-v2.print.io/Home#/orders/90073/summary
https://admin-v2.print.io/Home#/orders/33513/summary
https://admin-v2.print.io/Home#/orders/33468/summary
https://admin-v2.print.io/Home#/orders/33213/summary

**Comment by bomberaya** [comment]
@mkontic Bug confirmed - We are not uploading Prints properly (probably Professional prints too). I'm working on it.

**Comment by bomberaya** [comment]
@mkontic Fixed: v2.1.4

**Comment by Ivan1985** [comment]
Verified: 2.1.12

@bomberaya @mkontic @AustenB
