### ISSUE TITLE
Low/Medium: Choose options selection box not perfectly aligned

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#129]
All devices, newest versions of the SDK. 

Choose options selection box for products such as framed prints, canvas wraps and metal prints is not aligned with the product.

Notice how the selection box runs off the screen for the 4 photos layout:
![screenshot_2015-04-10-10-44-55](https://cloud.githubusercontent.com/assets/8051364/7092908/5dc329c8-df72-11e4-8168-c674838b7938.png)

Not aligned for the first layout:
![screenshot_2015-04-10-10-45-28](https://cloud.githubusercontent.com/assets/8051364/7092946/aae503ca-df72-11e4-9722-dfbe7461ea3c.png)

**Comment by vladopajic** [comment]
@itscam Fixed in 2.1.8, please verify.

**Comment by itscam** [comment]
@vladopajic Selection box on the far right no longer runs off the screen, but the other boxes touch product images. 

![screenshot_2015-04-11-14-58-12](https://cloud.githubusercontent.com/assets/8051364/7103571/6c1ed230-e06a-11e4-995c-bfb73374edc5.png)
![screenshot_2015-04-11-15-40-44](https://cloud.githubusercontent.com/assets/8051364/7103572/6c24d662-e06a-11e4-969f-ba3d6defc125.png)

**Comment by AustenB** [comment]
Also the text must be centered under the item.

On Sat, Apr 11, 2015 at 6:50 PM, Cameron Bradley <notifications@github.com>
wrote:

> @vladopajic <https://github.com/vladopajic> Selection box on the far
> right no longer runs off the screen, but the other boxes touch product
> images.
>
> [image: screenshot_2015-04-11-14-58-12]
> <https://cloud.githubusercontent.com/assets/8051364/7103571/6c1ed230-e06a-11e4-995c-bfb73374edc5.png>
> [image: screenshot_2015-04-11-15-40-44]
> <https://cloud.githubusercontent.com/assets/8051364/7103572/6c24d662-e06a-11e4-969f-ba3d6defc125.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/129#issuecomment-91937195>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio
