### ISSUE TITLE
High: Display issues on customize preview screen with newest sdk build

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#130]
GS5 and Moto G, SDK version 2.1.8 on production

Issue appears to affect framed prints, canvas wraps and metal prints

- Select framed prints, 14x14, single image
- Choose image from phone or Photobucket source and tap next

Observed: Image is not added to the preview. Sometimes the preview design shows a rectangular image, when the selected product should be a square.

With some products, such as the square 5x5 metal print(1st six image arrangement), the full collage preview is not displayed. Instead, the upper-left corner is displayed.
on the gs5:
![screenshot_2015-04-11-16-08-54](https://cloud.githubusercontent.com/assets/8051364/7103450/6d0994be-e065-11e4-89c3-feabc8e91f10.png)

Same product on Moto G:
![screenshot_2015-04-11-15-35-58](https://cloud.githubusercontent.com/assets/8051364/7103483/2dcdf3a2-e066-11e4-9971-c566f13e8458.png)

6x6 Square canvas wrap, second 3-photo layout:
![screenshot_2015-04-11-15-24-28](https://cloud.githubusercontent.com/assets/8051364/7103499/1777bcae-e067-11e4-98d8-a1732309db40.png)

**Comment by itscam** [comment]
@bomberaya @AustenB Sometimes when editing a product, the preview loads correctly.

![5secondsapp](https://cloud.githubusercontent.com/assets/8051364/7103562/07570426-e06a-11e4-9b3c-0e4f511220c3.gif)

**Comment by AustenB** [comment]
Does it always happen from editing an item already in the cart?

**Comment by itscam** [comment]
@AustenB No.

**Comment by bomberaya** [comment]
@itscam Fixed in v2.1.9, please verify
