### ISSUE TITLE
PB customer cannot apply a coupon for a tote bag

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-android-sdk#131]
We have a PB customer who cannot apply the coupon TOTE45, it says that the coupon cannot be applied to the item in the cart which is a tote bag.

The customer is using the app for their android phone, version is 3.3.5 and the phone is HTC One.

Please let me know if you need any further information!

@bomberaya  @ivan @AustenB 

![screenshot_2015-04-13-09-42-25](https://cloud.githubusercontent.com/assets/10880662/7117072/abab5a1c-e1f6-11e4-937b-2d04a66f2f04.png)

**Comment by AustenB** [comment]
The everything bag isn't a tote bag.

Tote bags are their own item.

**Comment by barnbucket** [comment]
I just checked in the admin panel and Everything bag is added as an eligible product for tote45.  @AustenB We renamed the everything bag.

**Comment by AustenB** [comment]
@barnbucket - perhaps the renaming caused the error?

We will look into it.

On Mon, Apr 13, 2015 at 10:36 AM, barnbucket <notifications@github.com>
wrote:

> I just checked in the admin panel and Everything bag is added as an
> eligible product for tote45. @AustenB <https://github.com/AustenB> We
> renamed the everything bag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/131#issuecomment-92383823>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by tamaratomovski** [comment]
Hey guys, I just wanted to follow up on this!

Thanks!

**Comment by AustenB** [comment]
@tamaratomovski @barnbucket 

I checked in admin and the everythingbag isn't added for this coupon

![image](https://cloud.githubusercontent.com/assets/7385040/7183991/b922348e-e428-11e4-824c-fef036ad2b3a.png)

**Comment by AustenB** [comment]
@barnbucket I just added it now - As you see on the 2nd line. So lets confirm that it works now in live

![image](https://cloud.githubusercontent.com/assets/7385040/7184030/f9748fe6-e428-11e4-8969-0f70953546d5.png)
