### ISSUE TITLE
Medium enhancement: External promo code is not automatically applied

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#133]
On iOS, promo codes that we display and pass through to the SDK are automatically applied when the product is added to the cart. On Android, the code is automatically entered but not applied. The user must tap on the promo code box and then tap apply.

**Comment by AustenB** [comment]
@itscam getting this enhancement done

**Comment by vladopajic** [comment]
@itscam Fixed in 2.1.9, please verify.
