### ISSUE TITLE
Activity_phone_case_grid layout is used for multiple products (not just phones)

### ISSUE THREAD

**Issue by KuchelD** [printdotio/printio-android-sdk#134]
On Android (not tested on iOS) the activity_phone_case_grid (Choose Options) layout appears to be used for multiple products such as Fleece Blankets,  Everything Bags, Mousepads etc.

The problem is there is background image of a mobile phone loaded as a placeholder image in the grid view in code not in the layout.  This occurs in the Step 1 and Step 2.

I recommend either loading a generic placeholder image rather than the mobile phone image (preferred) or just sticking with the existing progress spinner.

Example:
![image](https://cloud.githubusercontent.com/assets/5301032/7201542/b84bfc4e-e508-11e4-8501-55ab3417ec86.png)

**Comment by bomberaya** [comment]
@KuchelD Placeholders removed in v2.1.9
