### ISSUE TITLE
Metric and imperial measurement display issue

### ISSUE THREAD

**Issue by KuchelD** [printdotio/printio-android-sdk#136]
When testing in Australia or Germany I can for example add a Canvas Wrap with black size 30cm x 30cm but when viewing the item in the Shopping cart the SKU displayed is CanvsWrp-BlkWrp-12x12 ie 12 inches x 12 inches rather than 30 cm x 30 cm.

This is confusing for the customer when the sizing in the SKU description is different to size selected.

Perhaps it would be better to display to the user "Canvas Wrap - Black Wrap - 30 x 30cm" as a concatenated description of the choices made rather than the SKU. The SKU is for the printer not really for the customer.

Or we could add metric and imperial SKU's for each item is an option but I'm sure annoying for partners and printers. 

Another option is to add a metric and imperial SKU short description in database associated with the unique imperial SKU.  Then the correct SKU description could be displayed in the shopping cart based on current selected country rather than the actual SKU.  Not sure how this affects the customer invoicing process though (ie customer wants to see SKU in metric if purchased in metric).

**Comment by AustenB** [comment]
@KuchelD good idea -> we could change this across web, iOS, and Android.

**Comment by vladopajic** [comment]
Fixed in: 2.2.10
