### ISSUE TITLE
Medium enhancement: Communicate to cellular users that loading times will be much longer

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#137]
While building products over a cellular connection, I have experienced wait-times up to three minutes. These can take as little as 15-20 seconds when using a fast wi-fi connection. Can we make a note of this in the loading box? 

Something like "Loading... please note that loading times may vary based on connection."  or Loading... Wi-fi connection recommended."

**Comment by vladopajic** [comment]
@itscam Could you be more specific in which places you have experienced long wait times? 

On product building screens (choosing build options) all loadings should not last longer then a few seconds regardless of connectivity type. 
Places where link speed will make difference are when full size photos are being downloaded (on customization screens) and when photos are being uploaded (when sending order).

**Comment by itscam** [comment]
@vladopajic As you noted, the product customization screen while loading images, and when uploading images when sending order. Both of these can take several minutes when uploading over a cellular network.

**Comment by bomberaya** [comment]
Additional message is shown in Progress Dialog if network speed falls below a certain threshold.
