### ISSUE TITLE
Medium: Portrait image rotation issues for Flickr source

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#138]
Newest SDK, on production, all devices

When importing images from Flickr, I noticed that some images were not rotated correctly. The test uses images taken at the four major orientations from 0-270 degrees. Compare the following screenshots with the same Flickr images on Android and iOS, and notice that the portrait images were rotated incorrectly. 

![screenshot_2015-05-06-11-04-04](https://cloud.githubusercontent.com/assets/8051364/7498738/71908aa4-f3e0-11e4-8156-c85a709491b1.png)

![img_3824](https://cloud.githubusercontent.com/assets/8051364/7498745/8b55f334-f3e0-11e4-8b18-cd65855c88f6.PNG)

**Comment by vladopajic** [comment]
@itscam Fixed in 2.2.2, please verify.
