### ISSUE TITLE
Low/Medium: Thumbnail quality from Dropbox

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-android-sdk#139]
Newest SDK, on production, all devices.

Is it possible to grab a higher-quality thumbnail from the Dropbox source? The current thumbnail type is very low resolution.

![screenshot_2015-05-06-11-23-52](https://cloud.githubusercontent.com/assets/8051364/7499102/b1e367aa-f3e2-11e4-850e-946e00bba6be.png)

**Comment by vladopajic** [comment]
Hey @itscam,

Yes it is. We will increase size of thumbnails in next release.

**Comment by itscam** [comment]
Thanks @vladopajic

**Comment by vladopajic** [comment]
@itscam Fixed in 2.2.2, please verify.
