### ISSUE TITLE
Address validation issue 

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-android-sdk#141]
We have a customer who tried to place the order using Samsung Galaxy s6 and she is unable to do it because she is getting a message that the address is not validated.
I asked about the app version she's using, but she's not sure, and she is also unsure of the image sizes she tried to upload. 
She sent us one screen shot, please find it attached, but from the screen shot I can't really see the issue.
Is there anything we can do to assist her?

![address](https://cloud.githubusercontent.com/assets/8796232/8023069/f2eed6e6-0cf9-11e5-95a6-b876f6f444e0.png)

**Comment by vladopajic** [comment]
On android side we cant do much. She cant proceed because entered address is not valid - judged by our service. (https://staging.api.print.io/api/addressvalidation/?line1=405+4th+Lane&city=Greenacres&state=FL&postalCode=33463&countryCode=US&recipeid=00000000-0000-0000-0000-000000000000)

However, if address is valid then there is bug on server side.

**Comment by AustenB** [comment]
Tell her to try a different address and then to message us to change it

**Comment by AustenB** [comment]
@vladopajic try with her exact address and see if it works. Include screen shot here

**Comment by vladopajic** [comment]
@AustenB It does not work. In my previous comment is link with request to our address validation service with her exact address. Please, pay attention to `"IsValid":false` at the beginning of the response.

Screenshot:
![screenshot_2015-07-02-12-41-25](https://cloud.githubusercontent.com/assets/4353513/8475400/025a49f4-20b8-11e5-8163-33c5fdcf5d57.png)

**Comment by jovana-kovacevic** [comment]
Here's one more, please see the attachment.
![address validation](https://cloud.githubusercontent.com/assets/8796232/8904758/6d23f844-3462-11e5-8512-fe856cab885a.png)
He said
"I chose the shipping address from photobuckets drop down menu."

**Comment by jovana-kovacevic** [comment]
Hi guys, any progress on this?
Thank you!
@vladopajic @AustenB

**Comment by bomberaya** [comment]
Maybe @micahasmith can shed some light on this?

**Comment by micahasmith** [comment]
if address validation fails, the user should still be able to complete with the bad address.

if we're enforcing that only valid addresses get through, we're going to cut of a ton of customers

**Comment by AustenB** [comment]
Is Valid = False --> It might depend on the score.

What score is returned from these addresses?

@bomberaya

On Tue, Aug 4, 2015 at 11:28 AM, bomberaya <notifications@github.com> wrote:

> Maybe @micahasmith <https://github.com/micahasmith> can shed some light
> on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/141#issuecomment-127649193>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
@AustenB Well in the above example (link provided), we have isValid=false and score=95
```
{"IsValid":false,"Reason":"Score: 95. "...
```

@micahasmith Ok, and what about adresses with score lower than 77?

**Comment by AustenB** [comment]
@bomberaya -> put all addresses through to the next step ... addresses with
scores above 77 change the address to the one the server returns.

Else leave address as it is and continue forward.

It used to be set up this way -> not sure how it changed.

On Tue, Aug 4, 2015 at 11:45 AM, bomberaya <notifications@github.com> wrote:

> @AustenB <https://github.com/AustenB> Well in the above example (link
> provided), we have isValid=false and score=95
>
> {"IsValid":false,"Reason":"Score: 95. "...
>
> @micahasmith <https://github.com/micahasmith> Ok, and what about adresses
> with score lower than 77?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/141#issuecomment-127654784>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by vladopajic** [comment]
It's fixed. Fix will be available in following release.
