### ISSUE TITLE
Crash on Shopping Cart start in v2.3.0a

### ISSUE THREAD

**Issue by wrightcode** [printdotio/printio-android-sdk#143]
In the Photobucket application, after migrating to v2.3.0a, we get a crash when launching the print shop via the shopping cart menu item and when opening our sidebar menu and selecting print shop.  

Here is the stack trace.

06-30 09:14:27.270  19624-19624/com.photobucket.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.photobucket.android, PID: 19624
    java.lang.RuntimeException: Unable to resume activity {com.photobucket.android/print.io.ActivityShoppingCart}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String print.io.beans.Currency.format(java.lang.Object)' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3394)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.access$900(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String print.io.beans.Currency.format(java.lang.Object)' on a null object reference
            at gjln.a(Unknown Source)
            at gjln.a(Unknown Source)
            at print.io.ActivityShoppingCart.d(Unknown Source)
            at print.io.ActivityShoppingCart.onResume(Unknown Source)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
            at android.app.Activity.performResume(Activity.java:6412)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3383)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.access$900(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by AustenB** [comment]
Is this going straight to the shopping cart?

Can you email the init code you are running for these buttons specifically?

On Wed, Jul 1, 2015 at 12:15 PM, Jay Wright <notifications@github.com>
wrote:

> In the Photobucket application, after migrating to v2.3.0a, we get a crash
> when launching the print shop via the shopping cart menu item and when
> opening our sidebar menu and selecting print shop.
>
> Here is the stack trace.
>
> 06-30 09:14:27.270 19624-19624/com.photobucket.android E/AndroidRuntime﹕
> FATAL EXCEPTION: main
> Process: com.photobucket.android, PID: 19624
> java.lang.RuntimeException: Unable to resume activity
> {com.photobucket.android/print.io.ActivityShoppingCart}:
> java.lang.NullPointerException: Attempt to invoke virtual method
> 'java.lang.String print.io.beans.Currency.format(java.lang.Object)' on a
> null object reference
> at
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3394)
> at
> android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
> at
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
> at android.app.ActivityThread.access$900(ActivityThread.java:177)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:145)
> at android.app.ActivityThread.main(ActivityThread.java:5942)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual
> method 'java.lang.String print.io.beans.Currency.format(java.lang.Object)'
> on a null object reference
> at gjln.a(Unknown Source)
> at gjln.a(Unknown Source)
> at print.io.ActivityShoppingCart.d(Unknown Source)
> at print.io.ActivityShoppingCart.onResume(Unknown Source)
> at
> android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
> at android.app.Activity.performResume(Activity.java:6412)
> at
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3383)
> at
> android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
> at
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
> at android.app.ActivityThread.access$900(ActivityThread.java:177)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:145)
> at android.app.ActivityThread.main(ActivityThread.java:5942)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/143>.
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by wrightcode** [comment]
It happens when we start the shopping cart from our sidebar menu or the
shopping cart menu icon.

I've sent the apk and the init code to Bojan.

**Comment by AustenB** [comment]
Sounds good. We will get back to you ASAP.

On Wed, Jul 1, 2015 at 1:26 PM, Jay Wright <notifications@github.com> wrote:

> It happens when we start the shopping cart from our sidebar menu or the
> shopping cart menu icon.
>
> I've sent the apk and the init code to Bojan.
>
>
> On Wed, Jul 1, 2015 at 9:53 AM, Austen Bernstein <notifications@github.com
> >
> wrote:
>
> > Is this going straight to the shopping cart?
> >
> > Can you email the init code you are running for these buttons
> specifically?
> >
> > On Wed, Jul 1, 2015 at 12:15 PM, Jay Wright <notifications@github.com>
> > wrote:
> >
> > > In the Photobucket application, after migrating to v2.3.0a, we get a
> > crash
> > > when launching the print shop via the shopping cart menu item and when
> > > opening our sidebar menu and selecting print shop.
> > >
> > > Here is the stack trace.
> > >
> > > 06-30 09:14:27.270 19624-19624/com.photobucket.android
> E/AndroidRuntime﹕
> > > FATAL EXCEPTION: main
> > > Process: com.photobucket.android, PID: 19624
> > > java.lang.RuntimeException: Unable to resume activity
> > > {com.photobucket.android/print.io.ActivityShoppingCart}:
> > > java.lang.NullPointerException: Attempt to invoke virtual method
> > > 'java.lang.String print.io.beans.Currency.format(java.lang.Object)' on
> a
> > > null object reference
> > > at
> > >
> >
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3394)
> > > at
> > >
> android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
> > > at
> > >
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
> > > at android.app.ActivityThread.access$900(ActivityThread.java:177)
> > > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
> > > at android.os.Handler.dispatchMessage(Handler.java:102)
> > > at android.os.Looper.loop(Looper.java:145)
> > > at android.app.ActivityThread.main(ActivityThread.java:5942)
> > > at java.lang.reflect.Method.invoke(Native Method)
> > > at java.lang.reflect.Method.invoke(Method.java:372)
> > > at
> > >
> >
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> > > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> > > Caused by: java.lang.NullPointerException: Attempt to invoke virtual
> > > method 'java.lang.String
> > print.io.beans.Currency.format(java.lang.Object)'
> > > on a null object reference
> > > at gjln.a(Unknown Source)
> > > at gjln.a(Unknown Source)
> > > at print.io.ActivityShoppingCart.d(Unknown Source)
> > > at print.io.ActivityShoppingCart.onResume(Unknown Source)
> > > at
> > >
> >
> android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
> > > at android.app.Activity.performResume(Activity.java:6412)
> > > at
> > >
> >
> android.app.ActivityThread.performResumeActivity(ActivityThread.java:3383)
> > > at
> > >
> android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
> > > at
> > >
> android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
> > > at android.app.ActivityThread.access$900(ActivityThread.java:177)
> > > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
> > > at android.os.Handler.dispatchMessage(Handler.java:102)
> > > at android.os.Looper.loop(Looper.java:145)
> > > at android.app.ActivityThread.main(ActivityThread.java:5942)
> > > at java.lang.reflect.Method.invoke(Native Method)
> > > at java.lang.reflect.Method.invoke(Method.java:372)
> > > at
> > >
> >
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> > > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/printdotio/printio-android-sdk/issues/143>.
> > >
> >
> >
> >
> > --
> > Austen Bernstein
> > Founder & CEO
> > printio
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/printdotio/printio-android-sdk/issues/143#issuecomment-117748348
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/143#issuecomment-117757863>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by bomberaya** [comment]
@wrightcode Fixed in v2.3.8
