### ISSUE TITLE
App crashes during payment

### ISSUE THREAD

**Issue by rughvi** [printdotio/printio-android-sdk#144]
Hi team,
I downloaded the ANDROID SDK and added as a module to a project in android studio.
I set country as UK and then choose product as Metal Magnets and choose some local photos.
Added the product to the basket and in checkout entered my shipping details and during payment I chose PAY WITH CARD and after entering the card details clicked PAY which resulted in app crash. 
The error in the console is :

08-27 17:09:32.144    7137-7193/com.example.venkatp.printiomytestexample E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.example.venkatp.printiomytestexample, PID: 7137
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/services/s3/AmazonS3Client;
            at print.io.network.RestClient.uploadImage(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.doInBackground(Unknown Source)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.amazonaws.services.s3.AmazonS3Client" on path: DexPathList[[zip file "/data/app/com.example.venkatp.printiomytestexample-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at print.io.network.RestClient.uploadImage(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.a(Unknown Source)
            at wbyd.doInBackground(Unknown Source)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: com.amazonaws.services.s3.AmazonS3Client
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 12 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Any help is appreciated.
Regards,
Venkat V R

**Comment by AustenB** [comment]
Were you in the staging environment?

Payments in staging require test card info & might not work from simulator.

On Thu, Aug 27, 2015 at 12:18 PM, rughvi <notifications@github.com> wrote:

> Hi team,
> I downloaded the ANDROID SDK and added as a module to a project in android
> studio.
> I set country as UK and then choose product as Metal Magnets and choose
> some local photos.
> Added the product to the basket and in checkout entered my shipping
> details and during payment I chose PAY WITH CARD and after entering the
> card details clicked PAY which resulted in app crash.
> The error in the console is :
>
> 08-27 17:09:32.144 7137-7193/com.example.venkatp.printiomytestexample
> E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
> <https://github.com/printdotio/printio-android-sdk/issues/1>
> Process: com.example.venkatp.printiomytestexample, PID: 7137
> java.lang.RuntimeException: An error occured while executing
> doInBackground()
> at android.os.AsyncTask$3.done(AsyncTask.java:304)
> at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
> at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
> at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
> at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> at java.lang.Thread.run(Thread.java:818)
> Caused by: java.lang.NoClassDefFoundError: Failed resolution of:
> Lcom/amazonaws/services/s3/AmazonS3Client;
> at print.io.network.RestClient.uploadImage(Unknown Source)
> at wbyd.a(Unknown Source)
> at wbyd.a(Unknown Source)
> at wbyd.a(Unknown Source)
> at wbyd.doInBackground(Unknown Source)
> at android.os.AsyncTask$2.call(AsyncTask.java:292)
> at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>             at
> android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>             at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>             at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>             at java.lang.Thread.run(Thread.java:818)
> Caused by: java.lang.ClassNotFoundException: Didn't find class
> "com.amazonaws.services.s3.AmazonS3Client" on path: DexPathList[[zip file
> "/data/app/com.example.venkatp.printiomytestexample-2/base.apk"],nativeLibraryDirectories=[/vendor/lib,
> /system/lib]]
> at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
>             at print.io.network.RestClient.uploadImage(Unknown Source)
>             at wbyd.a(Unknown Source)
>             at wbyd.a(Unknown Source)
>             at wbyd.a(Unknown Source)
>             at wbyd.doInBackground(Unknown Source)
>             at android.os.AsyncTask$2.call(AsyncTask.java:292)
>             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>             at
> android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>             at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>             at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>             at java.lang.Thread.run(Thread.java:818)
> Suppressed: java.lang.ClassNotFoundException:
> com.amazonaws.services.s3.AmazonS3Client
> at java.lang.Class.classForName(Native Method)
> at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> ... 12 more
> Caused by: java.lang.NoClassDefFoundError: Class not found using the boot
> class loader; no stack available
>
> Any help is appreciated.
> Regards,
> Venkat V R
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-android-sdk/issues/144>.
>



-- 
Austen Bernstein
Founder & CEO
makeable

**Comment by bomberaya** [comment]
@rughvi Have you set your Braintree Encryption Key, as noted in Minimal Configuration here?  
https://github.com/printdotio/printio-android-sdk/blob/master/docs/QUICK_START_CODE.md#minimal-configuration

**Comment by rughvi** [comment]
@AustenB - I am using STAGING environment and on an android phone (not simulator). I am using a CITI CARD (visa) that has no more funds in it.

@bomberaya - I am setting the EncryptionKey as shown below

private void initSdkMode(boolean isLive) {
        config.setLiveApplication(isLive);

        String recipeId;
        String braintreeEncryptionKey;
        String payPalClientId;
        if (isLive) {
            recipeId = PIOConstants.RECIPE_ID_LIVE;
            braintreeEncryptionKey = PIOConstants.Braintree.ENCRYPTION_KEY_LIVE;
            payPalClientId = PIOConstants.PayPal.CLIENT_ID_LIVE;
        } else {
            recipeId = PIOConstants.RECIPE_ID_STAGING;
            braintreeEncryptionKey = PIOConstants.Braintree.ENCRYPTION_KEY_STAGING;
            payPalClientId = PIOConstants.PayPal.CLIENT_ID_STAGING;
        }
        config.setRecipeID(recipeId);
        config.setBraintreeEncryptionKey(braintreeEncryptionKey);
        config.setPayPalClientId(payPalClientId);

        if (config.isLiveApplication() || config.isLiveTestingApplication()) {
            config.setApiUrl(PublicConstants.API_URL_LIVE);
        } else {
            config.setApiUrl(PublicConstants.API_URL_STAGING);
        }
    }

**Comment by rughvi** [comment]
@AustenB - can you provide test card details please.

Ta.

**Comment by bomberaya** [comment]
@rughvi Is the Amazon AWS library added to the project?  
aws-android-sdk-1.7.0-s3.jar

**Comment by rughvi** [comment]
@bomberaya - my gradle has got the references to AWS jars.

dependencies {
    compile 'com.facebook.android:facebook-android-sdk:4.2.+'
    compile 'com.google.code.gson:gson:2.2.4'
    compile files('libs/aws-android-sdk.1.7.0-core.jar')
    compile files('libs/aws-android-sdk.1.7.0-s3.jar')
    compile files('libs/bugsense-3.5.jar')
    compile files('libs/braintree-android-encryption-1.0.0.jar')
    compile files('libs/bugsense-3.5.jar')
    compile files('libs/httpclientandroidlib-1.1.1.jar')
    compile files('libs/Parse-1.5.1.jar')
    compile files('libs/PayPalAndroidSDK-2.7.1.jar')
    compile files('libs/printiosdk.jar')
}

Regards,
Venkat

**Comment by rughvi** [comment]
@AustenB  - the card I am using is a CITI VISA from Nikon given to me as a cashback.
There are no funds in that card.

Can I have your mail Id so that I can drop you the card details confidentially.

**Comment by AustenB** [comment]
Staging requires test credentials from braintree.

4111111111111111

You can test with the above number for an amount under 1999

**Comment by bomberaya** [comment]
@rughvi Try doing a `gradle clean` (on Windows) or `./gradlew clean' (on Mac)

**Comment by rughvi** [comment]
@AustenB - I tried with the test card you have provided
Card No : 4111-1111-1111-1111
Expiry 06-2016
CVV : 001

Still getting the same exception.

**Comment by AustenB** [comment]
How much is the order for

.what country are you trying

What is the exact exemption

Email your initialization code to bojan@print.io and austen@print.io

**Comment by bomberaya** [comment]
This is not related to credit card, initialization code nor the order itself.
This has something to do with your project setup.
Have you tried performing gradle clean outside of Android Studio (using terminal/command prompt)?

**Comment by vladopajic** [comment]
@rughvi Hey Venkat,

Please, try this. In `build.gradle` file of your imported `printio` module change dependencies  to look like this:

```xml
dependencies {
    compile 'com.facebook.android:facebook-android-sdk:4.2.+'
    compile 'com.google.code.gson:gson:2.2.4'
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```

Regards,
Vlado

**Comment by rughvi** [comment]
@bomberaya  - done a ./gradlew clean from terminal
It did not help much.

**Comment by bomberaya** [comment]
@rughvi Which is the lowest Android SDK version that your application supports? It should not be lower than 10 (Android 2.3.3)

**Comment by rughvi** [comment]
@vladopajic - yuppie. changing the dependencies as you mentioned fixed the payment issue.
PS : Before this I have done a './gradlew clean'.
Thanks.
