### ISSUE TITLE
Configuring new photo source

### ISSUE THREAD

**Issue by rughvi** [printdotio/printio-android-sdk#145]
Hi team,
Is there a way I can configure AZURE STORAGE as a photo source in the SDK?
Regards,
Venkat V R

**Comment by vladopajic** [comment]
Hey Venkat,

Yeah, that is possible. We allow SDK users to create there own photo source(s). This [doc](https://github.com/printdotio/printio-android-sdk/blob/master/docs/CUSTOM_PHOTO_SOURCES.md) should be helpful to get you started.

Regards,
Vlado
