### ISSUE TITLE
Products for UK appear to be SOON in staging mode

### ISSUE THREAD

**Issue by rughvi** [printdotio/printio-android-sdk#146]
Hi team,
With the android sample app from github and for 
environment : STAGING 
country : UK 
there are only 5 products that can be ordered. Remaining others are coming SOON.

But with the below settings
environment : Production
country : UK 
none of the products are coming SOON. All of them are ready to be ordered.

I would like to know for UK which products are ready for ordering. 
(On other note my account for admin.print.io is disabled. I have already sent MAILS to print.io support. They are working on it. Until they fix it I can't access my account.)

Thanks,
Venkat V R

**Comment by bomberaya** [comment]
@rughvi This is a temporary issue on our side. It will be fixed today.

**Comment by rughvi** [comment]
@bomberaya - thanks. Let me know when this gets fixed.
I presume all the products that are being displayed for UK in PRODUCTION environment are available for ordering.

**Comment by bomberaya** [comment]
@rughvi I will let you know. Yes, that is true.

**Comment by bomberaya** [comment]
@rughvi Please let us know if this is no longer an issue, so we can close the ticket. Thanks :)
