### ISSUE TITLE
Crash after selecting "pay with paypal" option - Keepy

### ISSUE THREAD

**Issue by Debysh** [printdotio/printio-android-sdk#150]
Tested qith Android 4.4.4 - no paypal app installed in device 
Short description:
1. after adding product to shopping cart > "Check out"
2. Enter shipping details > select adress
3. Select "Pay with Paypal" option

**Comment by vladopajic** [comment]
Hello @Debysh,

Could you supply us with crash log? 

Thanks,
Vlado

**Comment by Debysh** [comment]
Hi Vlado, 
It seems this one was coming from our end - it was fixed with our following apk. Sorry to bother you on this.
Deby
