### ISSUE TITLE
NullPointerException: java.lang.String print.io.beans.Country.getCode()

### ISSUE THREAD

**Issue by dusanvita** [printdotio/printio-android-sdk#151]
Hi everyone, we just published the app with print.io included and got 4 crashes from 4 users already:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String print.io.beans.Country.getCode()' on a null object reference
       at uyzx.a()
       at print.io.ActivityProducts$5.run()
       at java.lang.Thread.run(Thread.java:818)

2 Samsung (SM G361F and SM G920F) 
2 Sony (D6503 and D6603)
all running Android 5.1.1

**Comment by vladopajic** [comment]
Hello @dusanvita,

What version of SDK is used? Could you give us the line number where this NullPointerException is thrown?

Thanks,
Vlado

**Comment by dusanvita** [comment]
Hi @vladopajic,
the one available on the github now (3.0.4)
If you need anything else, feel free to ask.

**Comment by bomberaya** [comment]
@dusanvita Let us know if this keeps happening with the latest version (3.1.0)

**Comment by dusanvita** [comment]
@bomberaya still happening in version 3.1.0...

**Comment by vladopajic** [comment]
Fixed in v3.1.19.
