### ISSUE TITLE
Font asset not found

### ISSUE THREAD

**Issue by dusanvita** [printdotio/printio-android-sdk#153]
Fonts offered in the app cannot be found in the files.

**Comment by bomberaya** [comment]
@dusanvita Fonts folder needs to be added to the assets folder of the host app.
The folder can be found in our Example app, here: https://github.com/printdotio/printio-android-example/tree/master/PIOSDKPOConcept/assets

Sorry, this is not properly documented.
We will make sure to add it to the documentation.

**Comment by dusanvita** [comment]
@bomberaya Cool, I got them! Thanks!
