### ISSUE TITLE
Hellopics customer - address validation failed

### ISSUE THREAD

**Issue by tamaratomovski** [printdotio/printio-android-sdk#157]
Hi guys!

We have a Hellopics customer who keeps getting the 'Address validation failed' warning when trying to place the order.

She has a Note 3 phone and here is the shipping address:

barbara head 
514 mccrary dr 
morristown tenn 37814

She uninstalled and installed the app back again and it is still showing this warning.

Could you please look into this?

Thanks,
Tamara

@bomberaya @Ivan1985 

![screenshot_2015-11-26-10-14-28](https://cloud.githubusercontent.com/assets/10880662/11441773/a7841fce-950f-11e5-9b40-1eb7e5de2534.png)
![screenshot_2015-11-26-10-36-17](https://cloud.githubusercontent.com/assets/10880662/11441774/a78f493a-950f-11e5-91f0-1b2e6f9b9a59.png)

**Comment by bomberaya** [comment]
Hi @tamaratomovski 

This issue has been resolved in PIO SDK v3.0.1
but we still haven't updated HelloPics app with the latest version :(

Take a look at this (same) issue:
https://github.com/printdotio/printio-android-sdk/issues/141

Is it possible to do what Austen suggested there:
"Tell her to try a different address and then to message us to change it"

**Comment by tamaratomovski** [comment]
Hi @bomberaya 

I'll suggest it to her and see how it goes from there.

Thanks! :)
