### ISSUE TITLE
Address validation failed - Hellopics app

### ISSUE THREAD

**Issue by mkontic** [printdotio/printio-android-sdk#158]
"I'm trying to order prints and ship it to my home, but I'm getting an error about it failing validation. I'm quite sure my address is correct.
I'm using the android app to sent my digital prints from dropbox. My shipping address is 4628 Demaree Ct, Henrico Va 23231."

![screenshot_2015-12-09-15-22-17](https://cloud.githubusercontent.com/assets/10849553/11746613/2f248030-a01f-11e5-9af2-9bde4a526028.png)

![screenshot_2015-12-09-15-22-26](https://cloud.githubusercontent.com/assets/10849553/11746614/3098f702-a01f-11e5-8541-55199778be19.png)

**Comment by vladopajic** [comment]
This issue has been fixed in v3.0.1.
