### ISSUE TITLE
Incorrectly generated images - order 451388

### ISSUE THREAD

**Issue by jovana-kovacevic** [printdotio/printio-android-sdk#165]
Hi guys!

We have an order where about 14 4x6 prints were generated incorrectly. The required size is 1800x1200 px and the generated images are 1200x1200 px.
The remaining images (169 of them) were generated properly.
Could you please look into this?

https://www.gooten.com/admin#/orders/451388/summary

Thanks!

**Comment by bomberaya** [comment]
@MilanDavid @stevanjoncic Were there any recent changes to the templates for "Print-Lustre-4x6"?
Generated image size is determined only by the data received from server.

**Comment by jovana-kovacevic** [comment]
Hi guys!
We fixed the images manually and pushed them to print, but could you please look into it?
Thank you!

**Comment by bomberaya** [comment]
Hi Jovana,

We'll take a look at the issue. Thanks :)

**Comment by bomberaya** [comment]
This seems like a serverside issue. Image sizes are defined by data from server. If the data is incorrect, generated images will also be incorrect.
