### ISSUE TITLE
The search bar only allows one letter and redundant magnify glass

### ISSUE THREAD

**Issue by Ckozoh** [printdotio/printio-android-sdk#39]
Samsung Galaxy S3 version 4.1.1
Photobucket version 3.3.0

In both the "Change Currency" and "Choose Country" the search bar only allows for 1 letter to be entered. To enter more letters you have to tap back on the search bar and repeat the process

![screenshot_2014-07-29-11-18-41](https://cloud.githubusercontent.com/assets/8116157/3738816/090bebfe-1745-11e4-8c74-a85e1a89b185.png)

I also noticed that there is a redundant magnifying glass on both of those pages. It starts out as an 'X' before any text has been entered and then after tapping on the 'X', it switches over to a magnifying glass which is also displayed above it

![screenshot_2014-07-29-11-23-22](https://cloud.githubusercontent.com/assets/8116157/3738981/c2c21c16-1746-11e4-89c7-8198f0877910.png)

![screenshot_2014-07-29-11-23-26](https://cloud.githubusercontent.com/assets/8116157/3738985/c889d3b4-1746-11e4-96a5-518c43802b8d.png)

**Comment by bomberaya** [comment]
Issue too old. Closing.
