### ISSUE TITLE
Edit mode with multiple photos are laggy and will occasionally crash app

### ISSUE THREAD

**Issue by Ckozoh** [printdotio/printio-android-sdk#61]
Samsung Galaxy S3 

-Create a product with multiple photos (I choose Canvas wrap w/ 36 photos and Frame prints w/ 24 photos)
-Tap on product in shopping cart
-Tap on edit

Observed:
Photos take a while to populate grid and bottom photo stream. It will also occasionally crash entire app

**Comment by bomberaya** [comment]
@Ckozoh Image downloading speed is limited by your Internet connection, and there is a limit on number of simultaneous downloads (n - 1; n -> number of cores on device's CPU).
We could try increasing this limit and see how well it performs.
Let's close this issue for now and open a separate issue if this is still a problem.
