### ISSUE TITLE
Low: Photo select should default back to photobucket if you don't log into another source

### ISSUE THREAD

**Issue by Ckozoh** [printdotio/printio-android-sdk#69]
If you tap on instagram for example and then don't log in, the photobucket source will appear but the Instagram source is still highlighted, not allowing you to go into any of the albums until you select photobucket as the main source again. Similar to issue #117 on iOS

![screenshot_2014-09-10-10-36-58](https://cloud.githubusercontent.com/assets/8116157/4221403/8ebd9e9c-3909-11e4-8309-9f0326444eb6.png)

**Comment by vladopajic** [comment]
Fixed in 2.1.9, please verify.
